#!/bin/bash 
# Author: Alexander David Leech
# Date:   9/1/2016
# Desc:   Script to start the system parameter identification tool.

clear
cd ../../src/systemParameterIdentification
echo Enter selection number:
echo '(1) Pre Sourced Data Tool'
echo '(2) Live Identification Tool'
read SELECTION

if [ $SELECTION -eq 1 ]
then
    echo 'Running identification on presourced data'
    python2 preSourcedDataID.py
    echo 'Press any key to exit...'         
    read DUMMY
    exit 1
fi

if [ $SELECTION -eq 2 ]
then
    echo 'Running identification on live system'
    echo 'Simulation Mode? [Y/N]'
    read SIM
fi    

if [ "$SIM" == "Y" ]
then
    python2 liveSystemParamID.py 1
    echo 'Press any key to exit...'         
    read DUMMY
    exit 1
fi

if [ "$SIM" == "N" ]
then
    python2 liveSystemParamID.py 0
    echo 'Press any key to exit...'         
    read DUMMY
    exit 1
fi

echo Invalid Input
exit 0