#!/bin/bash 
# Author: Alexander David Leech
# Date:   9/1/2016
# Desc:   Script to start the data logging tool

clear
cd ../src/dataLoggingTool
echo 'Simulation Mode? (Y/N)'
read SIM

if [ "$SIM" == "Y" ]
then
    python2 dataLoggingTool.py 1
    exit 1
fi

if [ "$SIM" == "N" ]
then
    python2 dataLoggingTool.py 0
    exit 1
fi
echo Invalid Input